version: "3"
services:
  
  nginx:
    image: bgornicki/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt

  engrave:
    image: bgornicki/engrave
    environment:
      # - DATABASE_URL=mongodb://mongo:27017/engrave
      # - STEEMCONNECT_REDIRECT_URI=http://localhost:8080/authorize/
      - DOMAIN=engrave.website
      - SSL_EMAIL=test@niepodam.pl
      - SSL_CERTIFICATES_DIR=/etc/letsencrypt
      - BLOGS_DOMAINS=["localhost", "localhost2"]
      - BLOGS_CATEGORIES=["Other"]
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - db-data:/data/db

volumes:
  db-data:
  nginx_certs:
  nginx_conf: