version: "3"
services:
  engrave:
    build: .
    ports: 
      - "8080:8080"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/engrave
      - PORT=8080
      - STEEMCONNECT_REDIRECT_URI=http://localhost:8080/authorize/
      - DOMAIN=engrave.website
      - SSL_EMAIL=test@niepodam.pl
      - SSL_CERTIFICATES_DIR=/etc/letsencrypt
      - BLOGS_DOMAINS=["engrave.website", "engrave.site"]
      - BLOGS_CATEGORIES=["Other"]
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    volumes:
      - db-data:/data/db

volumes:
  db-data: